server:
  port: 8080

spring:
  # H2 Console Path
  h2:
    console:
      enabled: true
      path: /h2-console

  # Security
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: "read:user,user:email"

  # JPA
  jpa:
    hibernate:
      ddl-auto: update

  # Datasource
  datasource:
    url: jdbc:h2:mem:devgrowth
    driverClassName: org.h2.Driver
    username: sa
    password: