spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: "read:user,user:email"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:devgrowth
    driverClassName: org.h2.Driver
    username: sa
    password:
server:
  port: 8080

h2:
  console:
    enabled: true
